#!/bin/bash

RELOAD() {
    echo "exit" > RELOAD
    zsh -i RELOAD
    rm RELOAD
    SOURCE build/VARS
}

bash build/UPDATE && RELOAD

bash build/PATH && RELOAD

bash build/PACKAGES && RELOAD

bash build/MAKEFILE
