#!/bin/bash

source etc/SETTINGS

RELOAD() {
    echo "exit" > .RELOAD
    zsh -i .RELOAD
    rm .RELOAD
}

# Define a function to execute a script and check for success
BUILD() {
    bash "$1" || exit 1  # Exit if any script fails
}

CLEAN() {
    rm -rf .tmp 
}

REBOOT() {
    sudo reboot
}

# List of SCRIPTS that need reloading after execution
SCRIPTS=(
    
    #"$CORE/SETUP"
    
    "$ENV/SETUP"
    
    
    "$USR/MAKEFILE"
    
    "$APPEARANCE/GTK"
    "$APPEARANCE/WM"
    "$APPEARANCE/ICONS"
    "$APPEARANCE/FONTS"
    "$APPEARANCE/CURSOR"
    "$APPEARANCE/TERMINAL"
    "$APPEARANCE/WALLPAPER"
    #"$APPEARANCE/XFCE"
    "$APPEARANCE/LIGHTDM"
    
    #"$PLUGINS/PICOM"
    #"$PLUGINS/EWW"
    #"$PLUGINS/DOCK"
    #"$PLUGINS/FINDEX"
    #"$PLUGINS/SCREENLOCK"
)

# Execute each script and reload only once at the end
for SCRIPT in "${SCRIPTS[@]}"; do
    BUILD "$SCRIPT"
done

# Reload once after all scripts have been executed
RELOAD

# Remove .tmp folder
#CLEAN

# Reboot system to load all the changes
#REBOOT
