#!/bin/bash

RELOAD() {
    echo "exit" > RELOAD
    zsh -i RELOAD
    rm RELOAD
}

# Define a function to execute a script and check for success
BUILD() {
    bash "$1" || exit 1  # Exit if any script fails
}

CLEAN() {
    rm -rf .tmp 
}

REBOOT() {
    sudo reboot
}

# List of SCRIPTS that need reloading after execution
SCRIPTS=(
    #"bash build/UPDATE"
    #"bash build/PATH"
    #"bash build/PACKAGES"
    "build/plugins/GENMON"
    #"build/RUST"
    "build/ENVIRONMENT"
    "build/LIGHTDM"
    "build/appearance/GTK"
    "build/appearance/WM"
    "build/appearance/ICONS"
    "build/appearance/FONTS"
    "build/appearance/CURSOR"
    "build/appearance/TERMINAL"
    "build/appearance/WALLPAPER"
    #"build/appearance/XFCE"
    #"build/plugins/PICOM"
    #"build/plugins/EWW"
    #"build/plugins/DOCK"
    #"build/plugins/FINDEX"
    #"build/plugins/SCREENLOCK"
)

# Execute each script and reload only once at the end
for SCRIPT in "${SCRIPTS[@]}"; do
    BUILD "$SCRIPT"
done

# Reload once after all scripts have been executed
RELOAD
